#This is make file for styles

#src path

base = base.css
components = components.css
filter = filter.css
home = home.css
items = items.css
item = item.css
payment = payment.css
popup = popup.css
slider = slider.css
table = table.css
carousel = carousel.css
discounted_items = discounted_items.css


files = ${base} ${components} ${home} ${payment.css} ${components} ${items} ${table} ${popup} ${slider} ${filter} ${carousel} ${discounted_items}

asales.css: ${files}
	cat > $@ $^

