#This is make file for styles

#src path

components =  components.css

items = items.css

table = table.css

popup = popup.css

files = ${components} ${items} ${table} ${popup}

asales.css: ${files}
	cat > $@ $^


