#This is make file for styles

#src path

base = base.css
components = components.css
filter = filter.css
home = home.css
items = items.css
payment = payment.css
popup = popup.css
slider = slider.css
table = table.css


files = ${base} ${components} ${home} ${payment.css} ${components} ${items} ${table} ${popup} ${slider} ${filter}


asales.css: ${files}
	cat > $@ $^


