#This is configuration file for asale application in appengine.

application: asales-dev
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /styles
  static_dir: static/styles

- url: /closure
  static_dir: ../../closure-library/closure

- url: /closure-templates
  static_dir: ../../closure-templates

- url: /images
  static_dir: static/images

- url: /js
  static_dir: static/js

- url: .*
  script: asales.app

libraries:
- name: webapp2
  version: "2.5.2"
- name: jinja2
  version: latest
